//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AniDeskimated.Resources {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LCS {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LCS() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AniDeskimated.Resources.LCS", typeof(LCS).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The Code Project Open License (CPOL) 1.02
        ///
        ///
        ///
        ///
        ///
        ///Preamble
        ///
        ///	This License governs Your use of the Work. This License is intended to allow developers
        ///	to use the Source Code and Executable Files provided as part of the Work in any
        ///	application in any form.
        ///
        ///
        ///	The main points subject to the terms of the License are:
        ///
        ///	Source Code and Executable Files can be used in commercial applications;
        ///	Source Code and Executable Files can be redistributed; and
        ///	Source Code can be modified to create derivati [stringa troncata]&quot;;.
        /// </summary>
        internal static string L_CPOL {
            get {
                return ResourceManager.GetString("L_CPOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a GNU GENERAL PUBLIC LICENSE
        ///Version 3, 29 June 2007
        ///
        ///Copyright © 2007 Free Software Foundation, Inc. &lt;https://fsf.org/&gt;
        ///
        ///Everyone is permitted to copy and distribute verbatim copies of this license document, but changing it is not allowed.
        ///
        ///Preamble
        ///The GNU General Public License is a free, copyleft license for software and other kinds of works.
        ///
        ///The licenses for most software and other practical works are designed to take away your freedom to share and change the works. By contrast, the GNU Genera [stringa troncata]&quot;;.
        /// </summary>
        internal static string L_GPL {
            get {
                return ResourceManager.GetString("L_GPL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a GNU LGPL 3.0 License
        ///----------------------------------------------------------------------------------------------------------------------------------------------------------------------
        ///Copyright © 2007 Free Software Foundation, Inc. &lt;https://fsf.org/&gt;
        ///
        ///Everyone is permitted to copy and distribute verbatim copies of this license document, but changing it is not allowed.
        ///
        ///This version of the GNU Lesser General Public License incorporates the terms and conditions of version 3 of the GNU General Public [stringa troncata]&quot;;.
        /// </summary>
        internal static string L_LGPL {
            get {
                return ResourceManager.GetString("L_LGPL", resourceCulture);
            }
        }
    }
}
